### ISSUE TITLE
Fresh installation of v0.8.5 stuck

### ISSUE THREAD

**Issue by nerd36** [ZeroNetX/zeronet_mobile#24]
Fresh installation of android v0.8.5 stuck at loading

**Comment by canewsin** [comment]
On Homepage or binary download page ?

**Comment by canewsin** [comment]
Fixed in https://github.com/ZeroNetX/zeronet_mobile/commit/bc15d8759627c837efe4dc2b7c55ffbe55d57334

**Comment by nerd36** [comment]
I mistakly created another [issue](https://github.com/ZeroNetX/zeronet_mobile/issues/28). Problem still exist in version 0.8.7. If it's trying to download a binary file,  you should embeded it in apk file. it would be more binary transparent, too.
